### ISSUE TITLE
PHP Strict Warning

### ISSUE THREAD

**Issue by arollmann** [yeesoft/yii2-yee-media#1]
I obtain the warning in attachment.

The problem is in yeesoft/yii2-yee-media/models/Media.php

Line 335 should be : 
public function search($params)
as in MediaSearch.php line 53.

PHP doesn't support traditional method overloading.
Cf. http://stackoverflow.com/questions/4697705/php-function-overloading

Best regards.

Alain Rollmann

![yee_warning](https://cloud.githubusercontent.com/assets/2589161/10818753/50668b50-7e44-11e5-961d-b105bc47b2ad.jpg)

**Comment by yeesoft** [comment]
Thank you. It is already fixed.
